name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    outputs:
      json_moved: ${{ steps.move_json_to_fosstars_folder.outputs.json_moved }}
    steps:
      - uses: actions/checkout@v3
      - uses: SAP/fosstars-rating-core-action@v1.14.0
        with:
          report-branch: ops/fosstars #TODO: Change to main
          report-file: .github/fosstars/fosstars_report.md
          badge-file: .github/fosstars/fosstars_badge.svg
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Move JSON to Fosstars folder
        id: move_json_to_fosstars_folder
        run: |
          if [ -e fosstars_rating.json ]; then
            echo "File exists."
            mv fosstars_rating.json .github/fosstars/
            echo "json_moved=true" >> "$GITHUB_OUTPUT"
          
            git config --global user.email "rachael.newbigging@sap.com"
            git config --global user.name "rnewbigging"
          
            echo "Working Repository: $GITHUB_REPOSITORY"
            echo "Current Branch: $GITHUB_REF"
            whoami 
            git status

            git add .github/fosstars/fosstars_rating.json fosstars_rating.json
            git commit -m "Move fosstars_rating.json to .github/fosstars/"
          
            git status
            git push origin ops/fosstars
          
          else
            echo "File does not exist."
            echo "json_moved=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  commit_and_push_changes:
#    runs-on: ubuntu-latest
#    needs: create_fosstars_report
#    if: needs.create_fosstars_report.outputs.json_moved == 'true'
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          token: "${{ secrets.GITHUB_TOKEN }}"
#
#      - name: Prepare git
#        run: |
#          git config --global user.email "rachael.newbigging@sap.com"
#          git config --global user.name "rnewbigging"
#
#      - name: Commit and push
#        run: |
#          echo "Working Repository: $GITHUB_REPOSITORY"
#          echo "Current Branch: $GITHUB_REF"
#          whoami
#          git status
#
#          git add .github/fosstars/fosstars_rating.json fosstars_rating.json
#          git commit -m "Move fosstars_rating.json to .github/fosstars/"
#
#          git status
#          git push origin ops/fosstars

#  open_and_merge_pull_request:
#    runs-on: ubuntu-latest
#    needs: create_fosstars_report
#    if: needs.create_fosstars_report.outputs.json_moved == 'true'
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          token: "${{ secrets.GITHUB_TOKEN }}"
#      - name: Commit and push changes
#        run: |
#          git config --global user.email "cloudsdk@sap.com"
#          git config --global user.name "SAP Cloud SDK Bot"
#          git checkout -b move-fosstars-rating-json
#          git add .github/fosstars/
#          git commit -m "Move fosstars_rating.json to .github/fosstars/"
#          git push --set-upstream origin move-fosstars-rating-json
#      - name: Open pull request
#        run: |
#          gh pr create --title "Move fosstars_rating.json" --body "Move fosstars_rating.json to .github/fosstars/"
#          gh pr review --approve
#          gh pr merge --auto --squash move-fosstars-rating-json