name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    outputs:
      json_file: ${{ steps.fosstars_rating.outputs.json_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create Fosstars report
        id: fosstars_rating
        uses: SAP/fosstars-rating-core-action@v1.14.0
        with:
          report-branch: ops/fosstars-report
          report-file: .github/fosstars/fosstars_report.md
          badge-file: .github/fosstars/fosstars_badge.svg
          token: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo fosstars_rating.json >> "$GITHUB_OUTPUT"
          

  move_json_file:
    runs-on: ubuntu-latest
    needs: create_fosstars_report
    env:
      JSON_FILE: ${{ needs.create_fosstars_report.outputs.json_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Prepare git
        run: |
          git config --global user.email "rachael.newbigging@sap.com"
          git config --global user.name "rnewbigging"

      - name: Move fosstars_rating.json
        run: |
          echo "$JSON_FILE"
          if [ -e $JSON_FILE ]; then
            echo "File exists."
            git pull origin ops/fosstars-report
            mv $JSON_FILE .github/fosstars/
            
            git add .github/fosstars/$JSON_FILE $JSON_FILE
            git commit -m "Move fosstars_rating.json to .github/fosstars/"

            git push origin ops/fosstars-report
          else
            echo "File does not exist."
          fi