name: "Fosstars (Security)"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SAP/fosstars-rating-core-action@v1.14.0
        with:
          report-branch: main
          report-file: .github/fosstars/fosstars_report.md
          badge-file: .github/fosstars/fosstars_badge.svg
          token: "${{ secrets.GITHUB_TOKEN }}"

  commit_and_push_changes:
    runs-on: ubuntu-latest
    needs: create_fosstars_report
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Prepare git
        run: |
          git config --global user.email "rachael.newbigging@sap.com"
          git config --global user.name "rnewbigging"

      - name: Move fosstars_rating.json
        run: |
          if [ -e fosstars_rating.json ]; then
            echo "File exists."
            git pull origin main
            mv fosstars_rating.json .github/fosstars/
            
            git add .github/fosstars/fosstars_rating.json fosstars_rating.json
            git commit -m "Move fosstars_rating.json to .github/fosstars/"

            git push origin main
          else
            echo "File does not exist."
          fi