name: "cf-test"

on:
  push:
    branches:
      - ops/e2e-action

env:
  BASIC_AUTH_ROUTE: "https://scp-cf-spring-e2e-test.internal.cfapps.sap.hana.ondemand.com"
  ODATA_PATH_AND_DESTINATIONS: "odata-v2?destination=QW9-HTTP-BASIC&destination=QM7-HTTP-BASIC"

jobs:
  curl-cf:
    runs-on: ubuntu-latest
    steps:
      - name: "Test CF Connection"
        run: |
          response=$(curl --fail -s -w "HTTP_STATUS_CODE:%{http_code}" ${BASIC_AUTH_ROUTE}/${ODATA_PATH_AND_DESTINATIONS})
          exit_code=$?

          if [ $exit_code -ne 0 ]; then
            echo "HTTP request failed with exit code: $exit_code"
            echo "Failure response body:"
            echo "$response"
          fi
          
          echo "Exit code of curl command: $exit_code"
          exit $exit_code